---
title: 'Application of `abmneo()` function to digestate storage'
output: pdf_document
vignette: >
  %\VignetteIndexEntry{Getting started with the abmneo() function}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
author: Sasha D. Hafner
date: "`r format(Sys.time(), '%d %B, %Y %H:%M')`"
---


# Parameters

```{r}
grp_VS_dig3 <- list(
  grps = c('m1', 'm2','m3','m4','m5'),
  yield = c(default = 0.05),
  xa_fresh = c(default = 0.06),
  xa_init = c(default = 0.06),
  d_max = c(default = 0.02),
  qhat_opt =  c(m1 = 1.6, m2 = 2.8, m3 = 6.2, m4 = 10, m5 = 16),
  T_opt = c(m1 = 18, m2 = 28, m3 = 36, m4 = 44, m5 = 55),
  T_min = c(m1 =  2, m2 =  2, m3 = 15, m4 = 26, m5 = 30),
  T_max = c(m1 = 25, m2 = 38, m3 = 45, m4 = 51, m5 = 60),
  ksmat = matrix(
    c(1.1, 1.1, 1.1, 1.1, 1.1),
    nrow = 1,
    byrow = TRUE,
    dimnames = list(
      c('VFA'),
      c('m1', 'm2', 'm3', 'm4', 'm5')
    )
  ),
  mstoich = matrix(
    c(
      -1, -1, -1, -1, -1,
       1,  1,  1,  1,  1
    ),
    nrow = 2,
    byrow = TRUE,
    dimnames = list(
      c('VFA', 'CH4'),
      c('m1', 'm2', 'm3', 'm4', 'm5')
    )
  )
)

sub_VS_dig3 <- list(
  subs = 'PS',
  sub_enrich = 'PS',
  xd = 'xd',
  h_rate_ref = c(default = 0.1),
  h_rate_q10 = c(default = 2),
  sub_fresh = c(PS = 18.22, xd = 0),
  sub_init  = c(PS = 18.22, xd = 0)
)

inf_VS_dig3 <- list(
  VFA_fresh = 0.5,
  VFA_init = 0.5,
  pH = 8,
  dens = 1000
)

```

With time series inputs.

```{r}
mass_series <- read.csv('level_pig_od_ref.csv') 
head(mass_series)
tail(mass_series)

stor_ser_ref <- list(
  type = 'series',
  dat = mass_series,
  storage_depth = 2,     
  area = 0.7,              
  temp_C = 18,
  resid_enrich = 0.2 
)
```

```{r}
devtools::load_all()
out_simp_ser <- abmneo(
  storage = stor_ser_ref,
  365,
  inf_pars = inf_VS_dig3,
  grp_pars = grp_VS_dig3,
  sub_pars = sub_VS_dig3,
  var_pars = list(var = temp_dat),
)
```

Plots next.
Methane emission rate, in g/d.

```{r}
plot(CH4_emis_rate ~ time, data = out_simp_ser, type = 'l')
```

And cumulative emission in g.

```{r}
plot(CH4 ~ time, data = out_simp_ser, type = 'l')
```

Microbial biomass (g).

```{r}
matplot(
  out_simp_ser$time, 
  out_simp_ser[, nn <- grp_VS_dig3$grps], 
  col = cc <- c('blue', 'orange', 'green', 'black', 'black', 'black', 'red'), 
  lty = 1:length(nn), type = 'l',
  ylab = 'Xa'
)
legend('topright', legend = nn, col = cc, lty = 1:length(nn))
```

And microbial biomass concentrations (g/kg).

```{r}
matplot(
  out_simp_ser$time, 
  out_simp_ser[, nn <- paste0(grp_VS_dig3$grps, '_conc')], 
  col = cc <- c('blue', 'orange', 'green', 'black', 'black', 'black', 'red'), 
  lty = 1:length(nn), 
  type = 'l',
  ylab = 'Xa conc'
)
legend('topright', legend = nn, col = cc, lty = 1:length(nn))
```

Substrate concentrations.

```{r}
matplot(
  out_simp_ser$time, 
  out_simp_ser[, nn <- paste0(sub_VS_dig3$subs, '_conc')], 
  col = cc <- c('blue', 'orange', 'green', 'black', 'red'), 
  lty = 1:length(nn), 
  type = 'l',
  ylab = 'Substrate conc.'
)
legend('topright', legend = nn, col = cc, lty = 1:length(nn))
```

And VFA mass and concentration.

```{r}
plot(VFA ~ time, data = out_simp_ser, type = 'l')
plot(VFA_conc ~ time, data = out_simp_ser, type = 'l')
```

Of course most of the temporal patterns are driven by slurry mass, which is also returned.

```{r}
plot(slurry_mass ~ time, data = out_simp_ser, type = 'l')
```



