---
title: 'abmneo() temperature response'
output: pdf_document
author: Sasha D. Hafner
date: "`r format(Sys.time(), '%d %B, %Y %H:%M')`"
---

# Overview
Exploration of temperature effects inspired by VanderZaag's 6 years of methane paper.

```{r}
devtools::load_all()
```

Set pars

Original ABM values from `ABM_fit/functions/setInitPars.R` at 1f98ed2590948562c24df9ac7272bf9c85c82f34.


```{r}
mstoich <- matrix(
  c(
    -1, -1, -1, -1, -1, -1, -1,
     0,  0,  0,  0,  0,  0, -0.50156,
     1,  1,  1,  1,  1,  1,  0
  ),
  nrow = 3,
  byrow = TRUE,
  dimnames = list(
    c('VFA', 'SO4', 'CH4'),
    c('m0', 'm1', 'm2', 'm3', 'm4', 'm5', 'sr1')
  )
)

mstoich

# For ksmat, SO4 value is from mic.pars2.0 in ABM repo
ksmat <- matrix(
  c(1.15, 1.15, 1.15, 1.15, 1.15, 1.15, 0.46,
      NA,   NA,   NA,   NA,   NA,   NA, 0.00694),
  nrow = 2,
  byrow = TRUE,
  dimnames = list(
    c('VFA', 'SO4'),
    c('m0', 'm1', 'm2', 'm3', 'm4', 'm5', 'sr1')
  )
)

ksmat
```

```{r}
grp_pars <- list(
  grps = c('m0', 'm1', 'm2','m3','m4','m5','sr1'),
  yield = c(default = 0.05, sr1 = 0.065),
  xa_fresh = c(m0 = 0.06, m1 = 0.06, m2 = 0.06, m3 = 0.06, m4 = 0.06, m5 = 0.06, sr1 = 0.06),
  xa_init = c(default = 0.1),
  d_max = c(default = 0.02),
  qhat_opt =  c(m0 = 0.46289, m1 = 0.74568, m2 = 0.9006605, m3 = 2.79672, m4 = 4.66012, m5 = 7.4601, sr1 = 0),
  T_opt = c(m0 = 18, m1 = 18, m2 = 28, m3 = 36, m4 = 43.75, m5 = 55, sr1 = 43.75),
  T_min = c(m0 = 0, m1 = 9.67, m2 = 9.67, m3 = 15, m4 = 26.25, m5 = 30, sr1 = 0),
  T_max = c(m0 = 25, m1 = 25, m2 = 38, m3 = 45, m4 = 51.25, m5 = 60, sr1 = 51.25),
  ksmat = ksmat,
  mstoich = mstoich
)

grp_pars
```

Influent pars from man_pars2.0.

```{r}
inf_pars <- list(
  VFA_fresh = 1.7, 
  VFA_init = 1.7,
  comps = c('SO4'),
  comp_fresh = c(SO4 = 0.2), 
  comp_init = c(SO4 = 0.2), 
  pH = 7, 
  dens = 1000
)
```

Slurry level and temperature, outdoor pig slurry tank

```{r}
mass_series <- read.csv('level_pig_od_ref.csv') 
plot(slurry_mass ~ time, data = mass_series, type = 'o')

stor_ser <- list(
  type = 'series',
  dat = mass_series,
  storage_depth = 2,     
  area = 0.03,              
  temp_C = 0,
  resid_enrich = 0.9 
)
```

Temperature

```{r}
temp_dat_cool <- data.frame(time = seq(0, 365, length.out = 53))
temp_dat_cool$temp_C <- 5 + 10 * sin((temp_dat_cool$time - 130) / 365 * 2 * pi)

temp_dat_hot <- data.frame(time = seq(0, 365, length.out = 53))
temp_dat_hot$temp_C <- 8 + 13 * sin((temp_dat_hot$time - 130) / 365 * 2 * pi)

plot(temp_C ~ time, data = temp_dat_cool, type = 'o', ylim = c(-5, 23))
lines(temp_C ~ time, data = temp_dat_hot, type = 'l')
```

Substrates and hydrolysis

```{r}
sub_pars <- list(
  subs = c('starch', 'Cfat', 'CPs', 'CPf', 'RFd'),
  sub_enrich = c('starch', 'Cfat', 'CPs', 'RFd'),
  xd = 'xd',
  arrA = c(starch = 0.557 * 3.61e12, Cfat = 0.557 * 3.61e12, CPs = 0.557 * 2.065 * 3.61e12, CPf = 0.557 * 2.065 * 3.61e12, RFd = 0.557 * 3.61e12, xd = 0.557 * 3.61e12),
  arrE = c(default = 8.16e4),
  sub_fresh = c(starch = 5.25, Cfat = 27.6, CPs = 21.1 * 0.55, CPf = 21.1 * 0.45, RFd = 25.4, xd = 0),
  sub_init = c(starch = 5.25, Cfat = 27.6, CPs = 21.1 * 0.55, CPf = 21.1 * 0.45, RFd = 25.4, xd = 0)
)
```

Chem pars.

```{r}
chem_pars <- list(COD_conv = c(CH4 = 5.32, SO4 = -1.9938), gases = c('CH4'))
```

Try to run

```{r}
devtools::load_all()

neo_out_cool <- abmneo(
  storage = stor_ser,
  365,
  delta_t = 1,
  inf_pars = inf_pars,
  grp_pars = grp_pars,
  sub_pars = sub_pars,
  chem_pars = chem_pars,
  var_pars = list(var = temp_dat_cool),
  startup = 2
)

neo_out_hot <- abmneo(
  storage = stor_ser,
  365,
  delta_t = 1,
  inf_pars = inf_pars,
  grp_pars = grp_pars,
  sub_pars = sub_pars,
  chem_pars = chem_pars,
  var_pars = list(var = temp_dat_hot),
  startup = 2
)
```

```{r}
plot(slurry_mass ~ time, data = neo_out_cool, type = 'l')
lines(slurry_mass ~ time, data = mass_series, type = 'l', col = 'red')

plot(slurry_depth ~ time, data = neo_out_cool, type = 'l')

plot(slurry_load ~ time, data = neo_out_cool, type = 'l')

plot(temp_C ~ time, data = neo_out_cool, type = 'l', col = 'blue')
lines(temp_C ~ time, data = temp_dat_cool, col = 'red')

plot(CH4_emis_rate ~ time, data = neo_out_cool, type = 'l', ylim = c(0, 3.2))

plot(CH4 ~ time, data = neo_out_cool, type = 'l')

matplot(
  neo_out_cool$time, 
  neo_out_cool[, nn <- grp_pars$grps], 
  col = cc <- c('blue', 'orange', 'green', 'black', 'black', 'black', 'red'), 
  lty = 1:length(nn), type = 'l',
  ylab = 'Xa'
)
legend('topright', legend = nn, col = cc, lty = 1:length(nn))

matplot(
  neo_out_cool$time, 
  neo_out_cool[, nn <- paste0(grp_pars$grps, '_conc')], 
  col = cc <- c('blue', 'orange', 'green', 'black', 'black', 'black', 'red'), 
  lty = 1:length(nn), 
  type = 'l',
  ylab = 'Xa conc'
)
legend('topright', legend = nn, col = cc, lty = 1:length(nn))

matplot(
  neo_out_cool$time, 
  neo_out_cool[, nn <- paste0(sub_pars$subs, '_conc')], 
  col = cc <- c('blue', 'orange', 'green', 'black', 'red'), 
  lty = 1:length(nn), 
  type = 'l',
  ylab = 'Substrate conc.'
)
legend('topright', legend = nn, col = cc, lty = 1:length(nn))

plot(VFA ~ time, data = neo_out_cool, type = 'l')

plot(VFA_conc ~ time, data = neo_out_cool, type = 'l')
```

```{r}
plot(temp_C ~ time, data = neo_out_cool, type = 'l', col = 'blue', ylim = c(-10, 25))
lines(temp_C ~ time, data = neo_out_hot, col = 'red')
```

```{r}
plot(CH4_emis_rate ~ time, data = neo_out_cool, type = 'l', col = 'blue', ylim = c(0, 3.2))
lines(CH4_emis_rate ~ time, data = neo_out_hot, col = 'red')
```
```{r}
plot(CH4 ~ time, data = neo_out_cool, type = 'l', col = 'blue', ylim = c(0, 200))
lines(CH4 ~ time, data = neo_out_hot, col = 'red')
```
